### PR TITLE
Correct usage of RecyclerView

### LINKED ISSUE #203: Incorrect Category List into APP
Firefly III Server Version: 5.6.10

Firefly III Mobile Version: 5.0.5

Android Version: 12

Device Information:

BRAND: Samsun
MODEL: A52
--------------------------------------
The category section was incorrec didn't show all value of the list at moment the list was restart again in the middle.

image

Current list on server after letter "C"
image

## Expected Behavior
Full list of category sorted

### PR DESCRIPTION
**Pull request by teldosas**
Fixes #203

## Type of change

- [X] Bug fix 
- [ ] New feature
- [ ] Translation

#203 appears to happen due to incorrect usage of the `RecyclerView`. After digging through the code I found that the same incorrect usage exists in other list-views as well (and I managed to reproduce the same bug in the other views as well). So this PR attempts to correct the usage in every place.

> When an item scrolls off the screen, RecyclerView doesn't destroy its view. Instead, RecyclerView reuses the view for new items that have scrolled onscreen. https://developer.android.com/guide/topics/ui/layout/recyclerview

### CODE REVIEW

File: app/src/main/java/xyz/hisname/fireflyiii/ui/categories/CategoriesRecyclerAdapter.kt [hunk 1]
```diff
@@ -30,28 +30,27 @@ import xyz.hisname.fireflyiii.repository.models.category.CategoryData
...
+    ): RecyclerView.ViewHolder(categoryView.root) {
+
         fun bind(categoryData: CategoryData, clickListener: (CategoryData) -> Unit) {
             val categoryDataSet = categoryData.categoryAttributes
-            binding.categoryName.text = categoryDataSet.name
-            binding.categoryId.text = categoryData.categoryId.toString()
-            binding.root.setOnClickListener { clickListener(categoryData) }
+            categoryView.categoryName.text = categoryDataSet.name
+            categoryView.categoryId.text = categoryData.categoryId.toString()
+            categoryView.root.setOnClickListener { clickListener(categoryData) }
```
Comment (teldosas) [inline app/src/main/java/xyz/hisname/fireflyiii/ui/categories/CategoriesRecyclerAdapter.kt:53]: When a category is about to scroll into view instead of updating the element is being recycled (and thus has scrolled out of view) the item that was stored in the `binding` field was used. That would render the recycled items unchanged appearing as if the list starts again from the beginning (#206). 

The existing implementation would not create any problems when one view is created for every list-item and thus no recycling is necessary (e.g. when the list is too short).

File: app/src/main/java/xyz/hisname/fireflyiii/ui/account/AccountRecyclerAdapter.kt [hunk 2]
```diff
@@ -32,57 +32,54 @@ import xyz.hisname.fireflyiii.util.extension.getCompatColor
...
+        val itemView = AccountListItemBinding.inflate(LayoutInflater.from(context), parent, false)
+        return AccountViewHolder(itemView)
     }
 
     override fun onBindViewHolder(holder: AccountViewHolder, position: Int){
         getItem(position)?.let{
             holder.bind(it, clickListener)
         }
-        // setIsRecyclable MUST BE SET TO false otherwise duplicate items will be shown
-        holder.setIsRecyclable(false)
```
Comment (teldosas) [inline app/src/main/java/xyz/hisname/fireflyiii/ui/account/AccountRecyclerAdapter.kt:52]: This seems to be a workaround for what this PR fixes

File: app/src/main/java/xyz/hisname/fireflyiii/ui/transaction/TransactionSeparatorAdapter.kt [hunk 3]
```diff
@@ -73,10 +68,13 @@ class TransactionSeparatorAdapter(private val clickListener:(Transactions) -> Un
         transactionModel.let { separator ->
             when(separator){
                 is SplitSeparator.SeparatorItem -> {
+                    val viewHolder = holder as SplitSeparatorViewHolder
+                    val separatorBinding = viewHolder.view
                     separatorBinding.separatorDescription.text = separator.description
                 }
                 is SplitSeparator.TransactionItem -> {
                     val viewHolder = holder as TransactionViewHolder
+                    val binding = viewHolder.view
```
Comment (teldosas) [inline app/src/main/java/xyz/hisname/fireflyiii/ui/transaction/TransactionSeparatorAdapter.kt:77]: Apparently the existing implementation won't create any problems here because the list-items don't have a defined height (https://stackoverflow.com/questions/63131286/android-recyclerview-doesnt-recycle-items). So, one view will be created for every item and no recycling will occur. But I think that it should be corrected anyway.

**Comment by emansih** [comment]
@teldosas Sorry I was busy the last couple of days and did not have a chance to review this code. It looks good and I am merging it. Thank you!
